apiVersion: apps/v1
kind: Deployment    
metadata:             
  name: angular-k8s-deployment
spec:               
  selector:         
    matchLabels:
      app: angular-k8s-deployment
  replicas: 3 
  template:
    metadata:
      labels:
        app: angular-k8s-deployment
    spec:
      containers:
        - name: angular-k8s-deployment
          image: azizbk9/angular-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-k8s-service
  labels:
    name: angular-k8s-deployment
spec:
  ports:
    - nodePort: 30170 # make the service available to network requests from external clients
      port: 80        # access the service via external port no
      targetPort: 80  # port number that container listening on
      protocol: TCP   
  selector:           
    app: angular-k8s-deployment
  type: NodePort
